[favv]
title = "Terugroepingen en waarschuwingen van producten"
url = "https://favv-afsca.be/nl/producten"
entrySelector = "div.view__content > ul li"
titleSelector = "div a .node__initiators .initiator"
linkSelector = "div a"

[biac]
title = "Brussels Airport Burenblog"
url= "https://www.brusselsairport.be/nl/neighbours-and-spotters/blog"
entrySelector = "div#vue-category-overview-list div.pressroom-news-item"
titleSelector = "a div.card-body h4.card-title"
linkSelector = "a"

[trenara]
title = "Trenara Blog"
url = "https://www.trenara.com/nl/blog"
entrySelector = "div[data-framer-name='Container'] div div[class*='-container']"
titleSelector="a[data-framer-name^='Variant'] div div[data-framer-name='Heading'] div[data-framer-name^='Lines'] p.framer-text"
linkSelector = "a[data-framer-name^='Variant']"
