[favv]
title = "Terugroepingen en waarschuwingen van producten"
url = "https://favv-afsca.be/nl/producten"
entrySelector = "div.view__content > ul li"
titleSelector = "div a .node__initiators .initiator"
linkSelector = "div a"

[biac]
title = "Brussels Airport Burenblog"
url= "https://www.brusselsairport.be/nl/neighbours-and-spotters/blog"
entrySelector = "div#vue-category-overview-list div.pressroom-news-item a"
titleSelector = "div.card-body h4.card-title"
linkSelector = ""
